#!/bin/bash
set -e

# ==============================================================================
# QuickPDF Platform - Production Deployment & Migration Script
# Ensures exact sequence: PostgreSQL generate -> PostgreSQL migrate -> build
# ==============================================================================

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
BACKEND_DIR="$ROOT_DIR/backend"

echo "=========================================================="
echo "🚀 QuickPDF Production Deployment Sequence"
echo "=========================================================="

cd "$BACKEND_DIR"

# 1. Environment & Pre-Flight Checks
echo "==> 1. Verifying Production Environment Variables..."
if [ -z "$DATABASE_URL" ]; then
  echo "❌ Error: DATABASE_URL is not set."
  echo "Expected format: postgresql://user:password@host:port/database"
  exit 1
fi

if [[ "$DATABASE_URL" != postgresql://* && "$DATABASE_URL" != postgres://* ]]; then
  echo "❌ Error: DATABASE_URL must start with postgresql:// or postgres://"
  exit 1
fi

if [ -z "$JWT_SECRET" ] || [ "${#JWT_SECRET}" -lt 32 ]; then
  echo "❌ Error: JWT_SECRET must be at least 32 characters in production."
  exit 1
fi

if [ -z "$SMTP_HOST" ] || [ -z "$SMTP_USER" ] || [ -z "$SMTP_PASS" ] || [ -z "$EMAIL_FROM" ]; then
  echo "❌ Error: SMTP credentials (SMTP_HOST, SMTP_PORT, SMTP_USER, SMTP_PASS, EMAIL_FROM) are mandatory in production."
  exit 1
fi

if [ -z "$STORAGE_ROOT" ]; then
  echo "❌ Error: STORAGE_ROOT is mandatory in production."
  echo "Expected format: absolute path, e.g. /var/lib/quickpdf/uploads"
  exit 1
fi

if [[ "$STORAGE_ROOT" != /* ]]; then
  echo "❌ Error: STORAGE_ROOT must be an absolute path (starting with /). Received: $STORAGE_ROOT"
  exit 1
fi

if [ -z "$JOB_SECRETS_ENCRYPTION_KEY" ] || [ "${#JOB_SECRETS_ENCRYPTION_KEY}" -lt 32 ]; then
  echo "❌ Error: JOB_SECRETS_ENCRYPTION_KEY is mandatory in production (at least 32 characters or 64 hex characters)."
  exit 1
fi

echo "✅ Environment variables verified."

# 2. Generate Prisma Client for PostgreSQL
echo "==> 2. Generating PostgreSQL Prisma Client..."
npx prisma generate --schema=prisma/schema.postgresql.prisma
echo "✅ PostgreSQL Prisma Client generated."

# 3. Apply PostgreSQL Migrations
echo "==> 3. Applying PostgreSQL Migrations..."
npx prisma migrate deploy --schema=prisma/postgresql/schema.prisma
echo "✅ PostgreSQL Migrations applied successfully."

# 4. TypeScript Production Build
echo "==> 4. Building production JavaScript bundle (tsc -> dist/)..."
npm run build
if [ ! -f "dist/server.js" ]; then
  echo "❌ Error: dist/server.js was not generated by TypeScript build."
  exit 1
fi
echo "✅ Production JavaScript bundle verified at dist/server.js."

echo "=========================================================="
echo "🎉 Production Deployment Sequence Completed Successfully!"
echo "Ready to start server: node dist/server.js (or npm start / pm2 / docker)"
echo "=========================================================="
